kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: exo-storage
nodes:
  - role: control-plane
    image: kindest/node:v1.31.0 # Cette version correspond mieux à  outil Kind v0.31
  - role: worker
    image: kindest/node:v1.31.0
  - role: worker
    image: kindest/node:v1.31.0
  - role: worker
    image: kindest/node:v1.31.0
