apiVersion: v1
kind: PersistentVolume
metadata:
  name: tasks-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/tmp/tasks-data" 
    type: DirectoryOrCreate