apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
  namespace: fullstack-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
        - name: users-container
          image: bounat/users-api:latest
          imagePullPolicy: IfNotPresent # dit à K8s de regarder en local d'abord
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          envFrom:
            - configMapRef:
                name: auth-access-config
