apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-2048
  labels:
    app: game-2048
spec:
  replicas: 2 # lance 2 copies du jeu pour la haute disponibilité
  selector:
    matchLabels:
      app: game-2048
  template:
    metadata:
      labels:
        app: game-2048
    spec:
      containers:
      - name: tomcat-2048
        image: quchaonet/2048
        ports:
        - containerPort: 8080 # Tomcat par défaut sur le 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service-2048
spec:
  type: LoadBalancer
  selector:
    app: game-2048
  ports:
    - protocol: TCP
      port: 80         # Port exposé à l'extérieur
      targetPort: 8080 # Port interne de Tomcat