apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-japan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-japan
  template:
    metadata:
      labels:
        app: express-japan
    spec:
    # 1. LA TOLÉRANCE (Le Pass pour passer les barrières de nœuds) permet au Pod de rentrer sur le nœud Japon malgré la Teinte.
      tolerations:
      - key: "country"
        operator: "Equal"
        value: "japan"
        effect: "NoExecute"
      affinity:
        # 2. L'AFFINITÉ (Le choix du nœud sur lequel le Pod doit s'installer) oblige le Pod à aller au Japon (il ne veut pas aller ailleurs).
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution: # signifie que si Kubernetes ne trouve pas de nœud avec le label japan, le Pod refusera de s'installer et restera en attente (Pending).
            nodeSelectorTerms:
            - matchExpressions:
              - key: country
                operator: In
                values: ["japan"]
      containers:
      - name: api
        image: bounat/node-api:v1 # image Node.js sur docker hub, construite à partir du Dockerfile de l'exercice 4