apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres-db
  namespace: postgres-ns

spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
      - name: postgres
        image: postgres:15

        resources:
          requests:
            memory: "128Mi"  # Ce qu'il réserve au minimum
            cpu: "100m"
          limits:
            memory: "256Mi"  # Le plafond maximum
            cpu: "500m"

        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD

        ports:
        - containerPort: 5432
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/postgresql/data # Chemin interne à Postgres
          
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: postgres-pvc