apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  storageClassName: ""
  
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeClaimPolicy: Retain
  hostPath:
    path: /mnt/data # Doit correspondre au containerPath de kind-config.yaml
    type: DirectoryOrCreate